Feature/responsive media field classes
EtchUK/Etch.OrchardCore.Fields pull request #81
Opened 2021-05-27 14:25 UTC by Newnab

Is this what you meant when we discussed this a while ago? :)

Intended outcome is a class like `hero__media--backgroundimage` on every responsive media field that isn't overridden.

2021-05-27 14:30 UTC, peterkeating requested changes
This is exactly what I meant. Be good to add it to the other fields.

2021-05-27 14:30 UTC, peterkeating commented on Views/ResponsiveMediaField.cshtml
> +    var cssClass = string.Format("{0}__media--{1}", Model.PartFieldDefinition.PartDefinition.Name, Model.PartFieldDefinition.Name);
I'd suggest using `$"{Model.PartFieldDefinition.PartDefinition.Name}__media--{Model.PartFieldDefinition.Name}" instead of `string.Format`.

2021-05-27 14:30 UTC, peterkeating commented on Views/ResponsiveMediaField.cshtml
> +        var listClass = string.Format("{0}__media-list--{1}", Model.PartFieldDefinition.PartDefinition.Name, Model.PartFieldDefinition.Name);
Put this in the top code block, so it's not mixed within the markup and change from `string.Format` to `$` interpolated string.

2021-05-27 14:34 UTC, Newnab commented
Are there specific fields which you think are good candidates for this, or is it just... All of 'em?

2021-05-27 14:34 UTC, peterkeating commented
> Are there specific fields which you think are good candidates for this, or is it just... All of 'em?

@Newnab All of them.

2021-05-27 14:35 UTC, Newnab commented
Okay cool - I might finish this PR up first and then make a note to open another with aaaaaall the other fields later.

2021-05-28 11:57 UTC, Newnab commented
Are you happy with the changes here Pete?

2021-05-28 12:57 UTC, peterkeating approved these changes

2021-06-16 07:44 UTC, merged